name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pylint-json2html
      - name: Analyse the code with pylint
        run: |
          pylint $(git ls-files '*.py') -f json > pylint_report.json || true
      - name: Convert Pylint JSON format
        run: |
          echo 'import json' > convert_pylint_json.py
          echo 'with open("pylint_report.json") as f:' >> convert_pylint_json.py
          echo '    data = json.load(f)' >> convert_pylint_json.py
          echo '    if isinstance(data, list):' >> convert_pylint_json.py
          echo '        data = {"messages": data}' >> convert_pylint_json.py
          echo 'with open("pylint_report_converted.json", "w") as f:' >> convert_pylint_json.py
          echo '    json.dump(data, f)' >> convert_pylint_json.py
          python convert_pylint_json.py
      - name: Convert Pylint report to HTML
        run: |
          pylint-json2html -f jsonextended -o pylint_report.html pylint_report_converted.json
      - name: Add HTML report to GitHub summary
        run: |
          echo '## Pylint Report' >> $GITHUB_STEP_SUMMARY
          echo '<details><summary>View Pylint Report</summary>' >> $GITHUB_STEP_SUMMARY
          echo '<!DOCTYPE html><html><body>' >> $GITHUB_STEP_SUMMARY
          cat pylint_report.html >> $GITHUB_STEP_SUMMARY
          echo '</body></html></details>' >> $GITHUB_STEP_SUMMARY
