# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow integrates Pyre with GitHub's
# Code Scanning feature.
#
# Pyre is a performant type checker for Python compliant with
# PEP 484. Pyre can analyze codebases with millions of lines
# of code incrementally – providing instantaneous feedback
# to developers as they write code.
#
# See https://pyre-check.org

name: Pyre

on:
  workflow_dispatch:
  push:
    branches: [ "master", "bugfix", "feature", "hotfix" ]
  pull_request:
    branches: [ "master", "bugfix", "feature", "hotfix" ]

permissions:
  contents: read
  security-events: write  # Required to create code scanning alerts

jobs:
  pyre:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version here, e.g., 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pyre
        uses: facebook/pyre-action@v2
        with:
          repo-directory: './'
          requirements-path: 'requirements.txt'
          # To customize these inputs:
          # See https://github.com/facebook/pyre-action#inputs
