# .github/workflows/python-app.yml
name: Python CI

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Set the Python version to 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest --cov=blog_platform --cov-report=xml --cov-report=html
      env:
        FLASK_ENV: testing  # Set environment variable for testing environment

    - name: Upload coverage report
      uses: codecov/codecov-action@v4.0.1
      with:
        files: coverage.xml  # Upload the coverage report to Codecov
        token: ${{ secrets.CODECOV_TOKEN }}  # Codecov token for uploading reports

    - name: Generate coverage HTML report
      run: |
        mkdir -p coverage
        cp -r htmlcov/* coverage/
      # Optional: Upload HTML coverage report artifacts
