# .github/workflows/python-app.yml
name: Python CI

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - master  # Trigger the workflow on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    services:
      postgres:
        image: postgres:14  # Use the PostgreSQL 14 Docker image
        ports:
          - 5432:5432  # Expose port 5432 for PostgreSQL
        env:
          POSTGRES_DB: blog_platform_test  # Set the default database name
          POSTGRES_USER: postgres  # Set the PostgreSQL user
          POSTGRES_PASSWORD: a  # Set the PostgreSQL password
        options: >-  # Using >- instead of > to remove trailing newlines
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Set the Python version to 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        FLASK_ENV: testing  # Set environment variable for testing environment
        DATABASE_URL: postgres://postgres:a@localhost:5432/blog_platform_test  # Set the database URL for testing
      run: |
        pytest --cov=blog_platform --cov-report=xml --cov-report=html

    - name: Upload coverage report
      uses: codec
